# **NumPy Basics**

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# 📖 TABLE OF CONTENTS

- [Setup](#Setup)
- [Introduction to NumPy and Array Creation Techniques](#Introduction-to-NumPy-and-Array-Creation-Techniques)
  - [What is an Array?](#What-is-an-Array?)
  - [Introduction to NumPy](#Introduction-to-NumPy)
  - [Creating Our First NumPy Array](#Creating-Our-First-NumPy-Array)
  - [Additional NumPy Array Creation Techniques](#Additional-NumPy-Array-Creation-Techniques)
  - [Lesson Summary](#Lesson-Summary)
- [Basic Array Operations in NumPy](#Basic-Array-Operations-in-NumPy)
  - [NumPy Array Addition and Subtraction](#NumPy-Array-Addition-and-Subtraction)
  - [NumPy Array Multiplication and Division](#NumPy-Array-Multiplication-and-Division)
  - [Explanation of Dot Product](#Explanation-of-Dot-Product)
  - [Lesson Summary](#Lesson-Summary)
- [Array Indexing and Slicing in NumPy](#Array-Indexing-and-Slicing-in-NumPy)
  - [Understanding Array Indexing](#Understanding-Array-Indexing)
  - [Unwrapping Array Slicing](#Unwrapping-Array-Slicing)
  - [Indexing and Slicing in Multi-dimensional Arrays](#Indexing-and-Slicing-in-Multi-dimensional-Arrays)
  - [Lesson Summary](#Lesson-Summary)
- [Array Shape and Reshape](#Array-Shape-and-Reshape)
  - [Understanding Shapes](#Understanding-Shapes)
  - [Investigating Array Shape](#Investigating-Array-Shape)
  - [Reshaping Array](#Reshaping-Array)
  - [Real Life Examples: Reshaping Arrays](#Real-Life-Examples:-Reshaping-Arrays)
  - [Lesson Summary](#Lesson-Summary)
- [Boolean Indexing and Fancy Indexing in NumPy](#Boolean-Indexing-and-Fancy-Indexing-in-NumPy)
  - [Practice with Boolean Indexing: Dataset](#Practice-with-Boolean-Indexing:-Dataset)
  - [Practice with Boolean Indexing: Boolean Mask](#Practice-with-Boolean-Indexing:-Boolean-Mask)
  - [Practice with Boolean Indexing: Selecting Data](#Practice-with-Boolean-Indexing:-Selecting-Data)
  - [Complex Filter Condition](#Complex-Filter-Condition)
  - [Introduction to Fancy Indexing](#Introduction-to-Fancy-Indexing)
  - [Practice with Fancy Indexing](#Practice-with-Fancy-Indexing)
  - [Lesson Summary](#Lesson-Summary)
- [Basic Statistical Operations in NumPy](#Basic-Statistical-Operations-in-NumPy)
  - [Mean, Median, Mode in NumPy](#Mean,-Median,-Mode-in-NumPy)
  - [Variance and Standard Deviation in NumPy](#Variance-and-Standard-Deviation-in-NumPy)
  - [Lesson Summary](#Lesson-Summary)
- [References](#References)

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# Setup

Before we jump in, let's quickly run the setup cell. It checks the environment (GPU, library versions) and sets random seeds for reproducibility — we want identical results on every run.

In [1]:
# 🔧 Setup: Run this cell first!
# Environment check + random seeds for reproducibility

import sys
import time
import random
import numpy as np
import pandas as pd
import matplotlib as mpl
import torch
import torch.nn as nn

print(f"📦 Python  {sys.version.split()[0]}")
print(f"🔢 NumPy   {np.__version__}")
print(f"📊 Matplotlib   {mpl.__version__}")
print(f"🔥 PyTorch {torch.__version__}")

# GPU check (only needed for optional deep-feature experiments)
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"✅ GPU available: {torch.cuda.get_device_name(0)}")
    print(f"   Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
else:
    device = torch.device("cpu")
    print("⚠️ No GPU detected")

DEVICE_LABEL = "GPU" if device.type == "cuda" else "CPU"

# Random seeds for reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

print(f"\n🎲 Random seed set to {SEED} (Python, NumPy, PyTorch)")

%matplotlib inline
%config InlineBackend.figure_format = 'jpeg'   # photos as JPEG, not PNG — ~10× smaller notebook
# Remove character limits for all columns of Pandas dataframes permanently in this session
pd.set_option('display.max_colwidth', None)

📦 Python  3.12.13
🔢 NumPy   2.0.2
📊 Matplotlib   3.10.0
🔥 PyTorch 2.11.0+cpu
⚠️ No GPU detected

🎲 Random seed set to 42 (Python, NumPy, PyTorch)


![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# Introduction to NumPy and Array Creation Techniques

## What is an Array?

An array in programming is a special variable that can hold several values of the same type at a time. Think of a bookshelf with books or a kitchen cabinet with dishes. Arrays make your program more organized and play a significant role in data analysis and data manipulation.

## Introduction to NumPy

Python doesn't have built-in support for arrays, but it does have a data structure called lists. Lists are versatile, but they are not optimized for mathematical operations. This is where the NumPy library comes in. NumPy provides support for arrays and a wide range of mathematical functions. When you think of arrays in Python, think of NumPy!

To use NumPy, import it into your Python program as follows: `import numpy as np`.

## Creating Our First NumPy Array

Let's create our first array using the `np.array()` function:

In [ ]:
import numpy as np

# Creating an array
arr1D = np.array([1, 2, 3, 4, 5])
print(f"Our first 1D array: {arr1D}")  # [1 2 3 4 5]

Our first 1D array: [1 2 3 4 5]


Here we've created an array `arr1D` that stores the numbers `1` to `5`. Now let's see how to access and modify these elements.

## Additional NumPy Array Creation Techniques

NumPy also provides functions to create arrays with default initial values. Let's check them:

In [ ]:
import numpy as np

# Array of all zeros
zeros = np.zeros(5)
print(f"All zeros: {zeros}")  # [0. 0. 0. 0. 0.]

# Array of all ones
ones = np.ones(5)
print(f"All ones: {ones}")  # [1. 1. 1. 1. 1.]

# Empty array
empty = np.empty(5)
print(f"Empty array: {empty}")  # May vary; random uninitialized numbers if seed not set

# Sequence of numbers in NumPy array
sequence = np.arange(0, 10, 2)
print(f"Sequence: {sequence}")  # [0 2 4 6 8]

All zeros: [0. 0. 0. 0. 0.]
All ones: [1. 1. 1. 1. 1.]
Empty array: [1. 1. 1. 1. 1.]
Sequence: [0 2 4 6 8]


These functions like `np.zeros()`, `np.ones()`, `np.empty()`, and `np.arange()` can quickly create arrays filled with specific values or a range of numbers. The arguments of the `np.arange()` function work similarly to the ones of the python's `range` function: the first value is the start of the sequence, the second one is the end of it, and the last one is the step.

## Lesson Summary

Excellent! Today, we mastered the importance of arrays, explored the **NumPy** library, and created our first NumPy array. Plus, we learned various built-in techniques to create arrays quickly using NumPy.

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# Basic Array Operations in NumPy

Welcome! Let's explore **Basic Array Operations** with `NumPy`, a powerful library for data analysis, machine learning, and scientific computing. We'll seek answers to questions like: How can arrays interact with one another? Can they be added, subtracted, multiplied, and divided? And if so, what insights can we gain from these operations?

"Basic Array Operations" refer to mathematical operations like addition, subtraction, multiplication, and division that are performed on arrays in an element-wise manner.

Consider two arrays representing yesterday's and today's temperatures. To find the change in temperature, you would subtract the `yesterday` array from the `today` array.

Ensure the arrays have the same shape before performing these operations!

## NumPy Array Addition and Subtraction

In `NumPy`, the `+` and `-` operators perform addition and subtraction operations, respectively, between arrays in an element-wise fashion.

Let's say you have arrays of products sold in two consecutive months. To find the total sales, simply add the arrays:

In [ ]:
import numpy as np

sales_month1 = np.array([120, 150, 90])
sales_month2 = np.array([130, 160, 80])
total_sales = sales_month1 + sales_month2
print(f"Total sales: {total_sales}")  # [250 310 170]

Total sales: [250 310 170]


Similarly, to find the difference in sales, subtract one array from the other:

In [ ]:
difference_sales = sales_month1 - sales_month2
print(f"Difference in sales: {difference_sales}")  # [-10 -10 10]

Difference in sales: [-10 -10  10]


## NumPy Array Multiplication and Division

Multiply or divide arrays using `*` and `/` operators in `NumPy`. They work element-wise as well.

Assume you have arrays of product prices and quantities sold. The total revenue can be found by multiplying:

In [ ]:
import numpy as np

prices = np.array([20, 30, 50])
quantities = np.array([100, 200, 150])
revenue = prices * quantities
print(f"Total revenue: {revenue}")  # [2000 6000 7500]

Total revenue: [2000 6000 7500]


Similarly, you might have an array of total revenue for each product and an array of units sold. To find the price per unit, simply divide the total revenue by the number of units sold:

In [ ]:
total_revenue = np.array([2000, 6000, 7500])
units_sold = np.array([100, 200, 150])
price_per_unit = total_revenue / units_sold
print(f"Price per unit: {price_per_unit}")  # [20. 30. 50.]

Price per unit: [20. 30. 50.]


## Explanation of Dot Product

The dot product is the sum of the product of corresponding elements in arrays. It is widely used in math and data analysis.

In [ ]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
dot_product = np.dot(array1, array2)
print(f"Dot product: {dot_product}")  # 32 (1 * 4 + 2 * 5 + 3 * 6 = 32)

Dot product: 32


## Lesson Summary

Today, we've explored `NumPy`'s **Basic Array Operations**, which are fundamental for tasks such as data analysis and machine learning. We've performed addition, subtraction, multiplication, and division operations on arrays, and computed the dot product of two arrays.

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# Array Indexing and Slicing in NumPy

Today, we are exploring **Array Indexing and Slicing**, two crucial concepts for data manipulation and processing. Utilizing Python's `NumPy` library, by the end of this lesson, you will be able to comfortably access and modify elements in a `NumPy` array.

## Understanding Array Indexing

Array indexing lets us access an element in an array. It works just like with Python's lists! Python uses zero-based indexing, meaning the first element is at position 0. Here's how we access elements:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)  # [1 2 3 4 5]
print(arr[0])  # 1
print(arr[2])  # 3
print(arr[-1])  # 5

[1 2 3 4 5]
1
3
5


Note that `[-1]` gives us the last element, the same as with plain Python's lists!

## Unwrapping Array Slicing

Array slicing lets us access a subset, or `slice`, of an array. The basic syntax for slicing in Python is `array[start:stop:step]`.

Let's check this out:

In [ ]:
print(arr)  # [1 2 3 4 5]
print(arr[1:4])  # [2 3 4]
print(arr[::2])  # [1 3 5]

[1 2 3 4 5]
[2 3 4]
[1 3 5]


As a reminder, `stop` is not included, so `[1:4]` gives us elements with indices 1, 2, 3. Also remember that we can skip any of arguments to make them default. Thus, `[::2]` specifies only the `step` parameter, so `start` and `end` are filled with the default value.

Let's recall the default values:
* start = 0
* end = len(array)
* step = 1

One important thing to know: if we modify elements in a sliced array, it also modifies the original array:

In [ ]:
print(arr)  # [1 2 3 4 5]
arr_slice = arr[1:4]
arr_slice[1] = 10

# Our original array changed too!
print(arr)  # [1 2 10 4 5]

[1 2 3 4 5]
[ 1  2 10  4  5]


## Indexing and Slicing in Multi-dimensional Arrays

Now, let's move to multi-dimensional arrays and try out these operations. We'll use a 2D array for illustration:

In [ ]:
arr_multi = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


We use comma-separated indices for each dimension to get elements from 2D arrays. Below, we get the entire second row or the entire third column:

In [ ]:
print(arr_multi[0, 2])  # 3
print(arr_multi[1])  # [4 5 6]
print(arr_multi[:, 2])  # [3 6 9]

3
[4 5 6]
[3 6 9]


Slicing on multi-dimensional arrays is also simple. We can retrieve the first two rows and first two columns, for instance:

In [ ]:
print(arr_multi[:2, :2])  # [[1, 2], [4, 5]]

[[1 2]
 [4 5]]


## Lesson Summary

Great job! You've learned how to manipulate arrays in Python using `NumPy`!

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# Array Shape and Reshape

Today we're focusing on **Array Shape** and **Reshape** in `NumPy`. Understanding an array's shape is like knowing the size of a box. Meanwhile, reshaping an array is like changing a box's dimensions to meet our needs.

## Understanding Shapes

The shape of an array is its dimensions, which are the sizes along each of its axes. Thus, understanding an array's shape helps us comprehend its structure. The concept of reshaping allows us to adjust the array's dimensions.

## Investigating Array Shape

`NumPy` provides an easy way to find an array's shape with the shape attribute.

In [ ]:
import numpy as np

# An array of toys
toys = np.array(['teddy bear', 'robot', 'doll', 'ball', 'yo-yo'])

# Print the no of toys
print(f"No of toys: {toys.shape}")  # (5,)

No of toys: (5,)


With a 2D array, the `shape` attribute returns a pair of numbers: the number of rows and columns.

In [ ]:
# Our toys divided into two boxes
toys_boxes = np.array([['teddy bear', 'robot', 'car'], ['doll', 'ball', 'yo-yo']])

# Print the shape of the toy boxes
print(f"Shape of the toy boxes: {toys_boxes.shape}")  # (2, 3)

Shape of the toy boxes: (2, 3)


## Reshaping Array

With NumPy's `reshape` method, we can flexibly change an array's shape without altering its data.

In [ ]:
# An array of toys
toys = np.array(['teddy bear', 'robot', 'car', 'doll', 'ball', 'yo-yo'])

# Reshape the array
toys_boxes = toys.reshape(3, 2)

print(f"toys_boxes:\n{toys_boxes}")
# [['teddy bear' 'robot']
#  ['car' 'doll']
#  ['ball' 'yo-yo']]

toys_boxes:
[['teddy bear' 'robot']
 ['car' 'doll']
 ['ball' 'yo-yo']]


## Real Life Examples: Reshaping Arrays

Reshaping arrays can be powerful in real-life scenarios. For example, if we're arranging alphabet blocks into a grid for a word puzzle, or if we're organizing family age data from a 1D array into a 2D array of generations and siblings. Here is the first example in code:

In [ ]:
# Let's create a list of alphabet blocks
blocks = np.array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'])

# Reshape it into a 3x3 grid
puzzle = blocks.reshape(3, 3)

print(f"Puzzle:\n{puzzle}")
# [['A' 'B' 'C']
#  ['D' 'E' 'F']
#  ['G' 'H' 'I']]

Puzzle:
[['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']]


## Lesson Summary

Well done, coder! You learned about array shape and reshaping in `NumPy`, practiced with real examples, and solidified your understanding.

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# Boolean Indexing and Fancy Indexing in NumPy

We'll explore a concept called Boolean Indexing in `NumPy` today. It lets us access array elements based on conditions instead of explicit indices.

## Practice with Boolean Indexing: Dataset

To illustrate, let's create a `NumPy` array, `data`:

In [2]:
import numpy as np

data = np.array([12, 43, 36, 32, 51, 18, 79, 7])
print(f"data: {data}")  # [12 43 36 32 51 18 79 7]

data: [12 43 36 32 51 18 79  7]


## Practice with Boolean Indexing: Boolean Mask

Now, suppose we want to extract elements greater than 30. We form a Boolean array checking this condition for `data`:

In [3]:
bool_array = data > 30
print(f"bool_array: {bool_array}")  # [False True True True True False True False]

bool_array: [False  True  True  True  True False  True False]


## Practice with Boolean Indexing: Selecting Data

To extract the elements that satisfy our condition from `data`, we use the `bool_array` as an index:

In [4]:
filtered_data = data[bool_array]
print(f"filtered_data: {filtered_data}")  # [43 36 32 51 79]

filtered_data: [43 36 32 51 79]


Now `filtered_data` only holds values from `data` that are greater than 30.

## Complex Filter Condition

We can also use Boolean conditions to combine multiple criteria using logical operators like `&` for AND and `|` for OR.

Consider an array of prices per unit for different products in a retail store:

In [5]:
prices = np.array([15, 30, 45, 10, 20, 35, 50])
print(f"prices: {prices}")  # [15 30 45 10 20 35 50]

prices: [15 30 45 10 20 35 50]


Suppose we want to find prices that are greater than 20 and less than 40. We can combine conditions using the `&` operator:

In [6]:
filtered_prices = prices[(prices > 20) & (prices < 40)]
print(f"Filtered Prices (20 < prices < 40): {filtered_prices}")  # [30 35]

Filtered Prices (20 < prices < 40): [30 35]


Now, let's consider finding prices that are either less than 15 or greater than 45 using the `|` operator:

In [7]:
filtered_prices_or = prices[(prices < 15) | (prices > 45)]
print(f"Filtered Prices (prices < 15 OR prices > 45): {filtered_prices_or}")  # [10 50]

Filtered Prices (prices < 15 OR prices > 45): [10 50]


Using these logical operators, you can create complex filtering conditions to extract exactly the data you need.

## Introduction to Fancy Indexing

Next, let's learn about **Fancy Indexing** in `NumPy`, a tool for accessing multiple non-adjacent array items. We pass an array of indices to select these items.

Consider an array of seven numbers:

In [8]:
data = np.array([11, 22, 33, 44, 55, 66, 77])
print(f"Data: {data}")  # [11 22 33 44 55 66 77]

Data: [11 22 33 44 55 66 77]


We fetch the 1st, 3rd, and 5th elements together:

In [9]:
fancy_indexes = np.array([0, 2, 4])
fancy_data = data[fancy_indexes]
print(f"Data from Fancy Indexing: {fancy_data}")  # [11 33 55]

Data from Fancy Indexing: [11 33 55]


## Practice with Fancy Indexing

Let's consider a practical use of Fancy Indexing. Given an array representing people's ages, we want to fetch the ages of person 2, person 5, and person 7:

In [10]:
ages = np.array([15, 22, 27, 35, 41, 56, 63, 74, 81])
print(f"Ages Array: {ages}")  # [15 22 27 35 41 56 63 74 81]

indexes = np.array([1, 4, 6])  # Indices of values of interest
fetched_ages = ages[indexes]
print(f"Fetched Ages: {fetched_ages}")  # [22 41 63]

Ages Array: [15 22 27 35 41 56 63 74 81]
Fetched Ages: [22 41 63]


## Lesson Summary

We've covered **Boolean Indexing** and **Fancy Indexing** in `NumPy` in today's session, moving from the basics to a more powerful, combined application of the methods.

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# Basic Statistical Operations in NumPy

Today, we'll learn about basic *statistical operations* using Python's `NumPy` library. These operations, including **mean, median, mode, variance,** and **standard deviation**, are vital tools for understanding and interpreting data. After learning each operation, we'll apply our understanding to a real-world dataset.

## Mean, Median, Mode in NumPy

The **mean**, or average, is the sum of all values divided by the number of values. In Python, we use `np.mean(array)` to calculate the mean. The **median** is the middle number in a sorted list, which can be calculated using `np.median(array)`. The **mode** is the most frequent value in your data set, which can be calculated using the `mode()` function from `scipy`'s `stats` module.

In [2]:
import numpy as np
from scipy import stats

grades = np.array([85, 87, 89, 82, 86, 80, 92, 80])
print(f"Mean: {np.mean(grades)}")  # 85.125
print(f"Median: {np.median(grades)}")  # 85.5
print(f"Mode: {stats.mode(grades)}")  # ModeResult(mode=80, count=2)

Mean: 85.125
Median: 85.5
Mode: ModeResult(mode=np.int64(80), count=np.int64(2))


Note that `stats.mode` returns an object. In case of a tie, this object contains multiple items. To obtain the actual mode value, we can select the first one of these items like this:

In [3]:
print(f"Mode: {stats.mode(grades)[0]}")  # 80

Mode: 80


## Variance and Standard Deviation in NumPy

**Variance** measures the spread of data, and the **standard deviation** is the square root of variance. Use `np.var(array)` and `np.std(array)` to calculate them as shown below:

In [4]:
print(f"Variance: {np.var(grades)}")  # 16.109375
print(f"Standard Deviation: {np.std(grades)}")  # 4.01364859

Variance: 16.109375
Standard Deviation: 4.013648589500581


## Lesson Summary

Congrats! You've learned basic statistical operations using `NumPy` and applied them to a real-world dataset. In this lesson, we introduced the **mean, median, mode, variance,** and **standard deviation** and calculated them using `NumPy` functions.

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# References

- **[CodeSignal: NumPy Basics Course](https://codesignal.com/learn/courses/numpy-basics)**

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)