# **Introduction to Linear Algebra for Machine Learning**

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# 📖 TABLE OF CONTENTS

- [Setup](#Setup)
- [Basics of Vectors and Matrices](#Basics-of-Vectors-and-Matrices)
  - [Concept: Vector](#Concept:-Vector)
  - [Creating and Displaying a Row Vector in Python](#Creating-and-Displaying-a-Row-Vector-in-Python)
  - [Creating and Displaying a Column Vector in Python](#Creating-and-Displaying-a-Column-Vector-in-Python)
  - [Concept: Matrix](#Concept:-Matrix)
  - [Creating and Displaying a Matrix in Python](#Creating-and-Displaying-a-Matrix-in-Python)
  - [Getting Dimensions in Python: Vectors](#Getting-Dimensions-in-Python:-Vectors)
  - [Getting Dimensions in Python: Matrices](#Getting-Dimensions-in-Python:-Matrices)
  - [Lesson Summary](#Lesson-Summary)
- [Basic Vector Operations](#Basic-Vector-Operations)
  - [Vector Addition: Introduction and Example](#Vector-Addition:-Introduction-and-Example)
  - [Vector Addition: Python Code](#Vector-Addition:-Python-Code)
  - [Scalar Multiplication: Introduction and Example](#Scalar-Multiplication:-Introduction-and-Example)
  - [Scalar Multiplication: Python Code](#Scalar-Multiplication:-Python-Code)
  - [Lesson Summary](#Lesson-Summary)
- [Basic Matrix Operations](#Basic-Matrix-Operations)
  - [Matrix Addition: Definition and Real-Life Analogy](#Matrix-Addition:-Definition-and-Real-Life-Analogy)
  - [Matrix Addition: Python Code](#Matrix-Addition:-Python-Code)
  - [Matrix Addition: Practical Example](#Matrix-Addition:-Practical-Example)
  - [Scalar Multiplication: Definition and Real-Life Analogy](#Scalar-Multiplication:-Definition-and-Real-Life-Analogy)
  - [Scalar Multiplication: Python Code](#Scalar-Multiplication:-Python-Code)
  - [Scalar Multiplication: Practical Example](#Scalar-Multiplication:-Practical-Example)
  - [Lesson Summary](#Lesson-Summary)
- [Dot Product and Matrix Multiplication](#Dot-Product-and-Matrix-Multiplication)
  - [Dot Product](#Dot-Product)
  - [Real-Life Example of Dot Product](#Real-Life-Example-of-Dot-Product)
  - [Dot Product: Python Code](#Dot-Product:-Python-Code)
  - [Matrix Multiplication](#Matrix-Multiplication)
  - [When Matrices Can Be Multiplied: Example 1](#When-Matrices-Can-Be-Multiplied:-Example-1)
  - [When Matrices Can Be Multiplied: Example 2](#When-Matrices-Can-Be-Multiplied:-Example-2)
  - [When Matrices Can Be Multiplied: Example 3](#When-Matrices-Can-Be-Multiplied:-Example-3)
  - [Real-Life Example of Matrix Multiplication](#Real-Life-Example-of-Matrix-Multiplication)
  - [Matrix Multiplication: Python Code](#Matrix-Multiplication:-Python-Code)
  - [Lesson Summary](#Lesson-Summary)
- [References](#References)

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# Setup

Before we jump in, let's quickly run the setup cell. It checks the environment (GPU, library versions) and sets random seeds for reproducibility — we want identical results on every run.

In [1]:
# 🔧 Setup: Run this cell first!
# Environment check + random seeds for reproducibility

import sys
import time
import random
import numpy as np
import pandas as pd
import matplotlib as mpl
import torch
import torch.nn as nn

print(f"📦 Python       {sys.version.split()[0]}")
print(f"🔢 NumPy        {np.__version__}")
print(f"🐼 Pandas       {pd.__version__}")
print(f"📊 Matplotlib   {mpl.__version__}")
print(f"🔥 PyTorch      {torch.__version__}")

# GPU check (only needed for optional deep-feature experiments)
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"✅ GPU available: {torch.cuda.get_device_name(0)}")
    print(f"   Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
else:
    device = torch.device("cpu")
    print("⚠️ No GPU detected")

DEVICE_LABEL = "GPU" if device.type == "cuda" else "CPU"

# Random seeds for reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

print(f"\n🎲 Random seed set to {SEED} (Python, NumPy, PyTorch)")

%matplotlib inline
%config InlineBackend.figure_format = 'jpeg'   # photos as JPEG, not PNG — ~10× smaller notebook
# Remove character limits for all columns of Pandas dataframes permanently in this session
pd.set_option('display.max_colwidth', None)

📦 Python       3.13.15
🔢 NumPy        2.1.3
🐼 Pandas       2.2.3
📊 Matplotlib   3.10.0
🔥 PyTorch      2.11.0+cpu
⚠️ No GPU detected

🎲 Random seed set to 42 (Python, NumPy, PyTorch)


![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# Basics of Vectors and Matrices

Welcome to our lesson on the basics of **vectors** and **matrices**!

In this lesson, we'll explore what vectors and matrices are, why they're important in machine learning, and how to create and work with them in Python. By the end of this lesson, you'll understand how to define, display, and interpret vectors and matrices. Let's get started!

## Concept: Vector

Imagine you have a list of your favorite ice cream flavors: `["vanilla", "chocolate", "strawberry"]`. A vector is such a list, but with numbers. For example, a vector could be `[1, 2, 3]`.

A vector is a list (or array) of numbers arranged in a specific order. It's one-dimensional, meaning it has only one row or one column. If a vector is a row, it is called a **row vector**. Here is an example of it:
\begin{equation*}
[1 \quad 2 \quad 3]
\end{equation*}

If a vector is a column, it is called a **column vector**:
\begin{equation*}
\begin{bmatrix}
1 \\
2 \\
3
\end{bmatrix}
\end{equation*}

They look the same, but some mathematical operations treat row vectors and column vectors differently, so it is vital to differentiate them.

## Creating and Displaying a Row Vector in Python

Let's see how we can create a row vector in Python using `np.array()` from the NumPy library. NumPy provides advanced linear algebra features that will be useful in the upcoming units of our course.

In [ ]:
import numpy as np

# Create a row vector
vector = np.array([1, 2, 3])

# Display the vector
print(f'Vector:\n{vector}')

Vector:
[1 2 3]


This shows a simple row vector with three numbers.

## Creating and Displaying a Column Vector in Python

And this is how we represent the column vector using `np.array()`:

In [ ]:
import numpy as np

# Create a column vector
vector = np.array([
    [1],
    [2],
    [3]
])

# Display the vector
print(f'Vector:\n{vector}')

Vector:
[[1]
 [2]
 [3]]


Using `np.array()`, we specify a 2-dimensional structure for the column vector, but with one item in each row.

## Concept: Matrix

Now, imagine you have a class of students, and you want to record their scores in three subjects: Math, Science, and English. You can use a matrix for this. A matrix looks like a grid, with numbers arranged in rows and columns; each number represents a score.

Here is an example matrix:
\begin{equation*}
\begin{bmatrix}
95 & 88 & 92 \\
85 & 90 & 87 \\
78 & 85 & 80
\end{bmatrix}
\end{equation*}

Each row could represent the scores for a single student, and each column – a separate subject. As we have `3` students and `3` subjects, the matrix is a square one.

Let's take this example further. Imagine there are `5` students in the class. In this case, the corresponding matrix will be rectangular:
\begin{equation*}
\begin{bmatrix}
95 & 88 & 92 \\
85 & 90 & 87 \\
78 & 85 & 80 \\
85 & 90 & 82 \\
75 & 77 & 99
\end{bmatrix}
\end{equation*}

A matrix can be of any form. In machine learning, you will mostly deal with large rectangular matrices.

## Creating and Displaying a Matrix in Python

Next, let's create a matrix using `np.array()`:

In [ ]:
import numpy as np

# Create a matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Display the matrix
print(f'Matrix:\n{matrix}')

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


This is a 3x3 matrix, represented with a 2-dimensional NumPy array.

## Getting Dimensions in Python: Vectors

Understanding the dimensions of vectors and matrices is essential for many operations in machine learning.

Let's see how to print the length of a vector:

In [ ]:
import numpy as np

# Create a row vector
row_vector = np.array([1, 2, 3])
print(f'Length of the row vector: {len(row_vector)}')

# Create a column vector
column_vector = np.array([
    [1],
    [2],
    [3]
])
print(f'Length of the column vector: {column_vector.shape[0]}')

Length of the row vector: 3
Length of the column vector: 3


For `np.array()`, the length of a row vector can be found using `len()`, and for a column vector, we use the `.shape` attribute to get the number of rows.

## Getting Dimensions in Python: Matrices

Here's how to get the number of rows and columns in a matrix:

In [ ]:
import numpy as np

# Create a matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(f'No of rows: {matrix.shape[0]}')
print(f'No of columns: {matrix.shape[1]}')

No of rows: 3
No of columns: 3


Using the `.shape` attribute of `np.array()`, we can easily access both the number of rows and columns in a matrix.

Now you know how to create and display vectors and matrices and determine their dimensions using `np.array()` from the NumPy library.

## Lesson Summary

To sum up, we’ve learned the concepts of vectors and matrices and how to create and display them in Python using `np.array()`. Vectors are one-dimensional arrays of numbers, while matrices are two-dimensional grids. Understanding these basics is crucial as they are the building blocks for many operations in machine learning.

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# Basic Vector Operations

Today, we're diving into basic **vector operations**, which are foundational to your journey in **machine learning**. Understanding these operations will help you grasp more complex concepts later on. Our goals are to learn **vector addition** and **scalar multiplication**. We'll see why these operations are essential, learn how to implement them in Python, and understand their real-world applications.

## Vector Addition: Introduction and Example

Imagine you have two lists of numbers. You want to combine them by adding corresponding numbers together. That's `vector addition`. Let's say we have vector $v_1 = [1, 2, 3]$ and vector $v_2 = [4, 5, 6]$. Adding these vectors gives us another vector where each element is the sum of the corresponding elements.

**Note:** The vectors must be of the same length to perform this addition.

So, $v_1 + v_2 = [1+4, 2+5, 3+6] = [5, 7, 9]$.

Consider two delivery trucks: Truck A and Truck B. Truck A delivers 1, 2, and 3 packages to three different locations respectively, while Truck B delivers 4, 5, and 6 packages to the same locations. By using vector addition, we can determine the total number of packages delivered to each location as follows: [1+4, 2+5, 3+6] = [5, 7, 9]. This means the total packages delivered to each location are 5, 7, and 9 respectively.

## Vector Addition: Python Code

Here's how we can implement the vector addition in python:

In [ ]:
import numpy as np

# Vector addition using NumPy
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(f'Vector addition: {v1 + v2}')

Vector addition: [5 7 9]


Let's break down the code:
* `np.array([1, 2, 3])` and `np.array([4, 5, 6])` create numpy arrays for `v1` and `v2`.
* The expression `v1 + v2` performs element-wise addition, resulting in `[5, 7, 9]`.

## Scalar Multiplication: Introduction and Example

Imagine you have a list of numbers and you want to multiply each number by a constant value (scalar). For example, if $v = [2, 4, 6]$ and the scalar is 3, then multiplying each element by 3 gives us $3v = [6, 12, 18]$.

Imagine you are running a business and you have a list of product prices that are expected to increase by a fixed percentage (e.g., 20%). If the current prices are [10, 20, 30] dollars and you want to apply a 20% increase, you would multiply each price by 1.2. The new prices would be $[10 \times 1.2, 20 \times 1.2, 30 \times 1.2] = [12, 24, 36]$ dollars.

## Scalar Multiplication: Python Code

Here's the Python code for the scalar multiplication:

In [ ]:
import numpy as np

# Scalar multiplication using NumPy
v1 = np.array([1, 2, 3])
scalar = 2

print(f'Scalar multiplication: {scalar * v1}')

Scalar multiplication: [2 4 6]


Explanation:
* The scalar `2` is multiplied with each element in the numpy array `v1` using the expression `scalar * v1`.
* This results in `[2*1, 2*2, 2*3]`, or `[2, 4, 6]`.

## Lesson Summary

In this lesson, we covered:
* **Vector Addition**: Combining elements from two lists element-wise.
* **Scalar Multiplication**: Multiplying each element in a list by a constant value.

These operations are fundamental in machine learning and data science. By understanding and performing them in Python, you are building a solid foundation for more advanced topics.

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# Basic Matrix Operations

In this lesson, we're diving into basic **matrix operations** used in *machine learning*. Understanding matrix operations is crucial because they underpin many algorithms in this field.

Today's goal is to learn **matrix addition** and **scalar multiplication**. By the end, you'll be able to add two matrices and multiply a matrix by a scalar using Python and NumPy.

## Matrix Addition: Definition and Real-Life Analogy

Matrix addition involves adding corresponding elements from two matrices. Imagine you have two grids of numbers and you want to create a new grid where each number is the sum of the corresponding numbers from the original grids.

Think of each matrix as a seating chart for two classrooms. Adding the matrices is like finding the total number of students in the same seats in both charts.

## Matrix Addition: Python Code

To add two matrices, they must have the same dimensions. Here's how you can do it in Python with NumPy:

In [ ]:
import numpy as np

# Example matrices
m1 = np.array([[1, 2, 3], [4, 5, 6]])
m2 = np.array([[7, 8, 9], [10, 11, 12]])

# Adding matrices
result = m1 + m2
print(f'Matrix Addition:\n{result}')

Matrix Addition:
[[ 8 10 12]
 [14 16 18]]


1. `np.array()` creates NumPy arrays from the provided lists.
2. `m1 + m2` adds the corresponding elements of `m1` and `m2`. This sums elements at the same positions in both matrices to form a new matrix.

## Matrix Addition: Practical Example

Suppose you manage inventory for two warehouses. Each warehouse has a matrix representing the quantity of different products in different sections. By adding the two matrices, you can find the total quantity of each product across both warehouses.

In [ ]:
import numpy as np

# Warehouse 1 inventory
warehouse1 = np.array([[10, 20, 30], [40, 50, 60]])

# Warehouse 2 inventory
warehouse2 = np.array([[5, 15, 25], [35, 45, 55]])

# Total inventory
total_inventory = warehouse1 + warehouse2
print(f'Total Inventory:\n{total_inventory}')

Total Inventory:
[[ 15  35  55]
 [ 75  95 115]]


## Scalar Multiplication: Definition and Real-Life Analogy

**Scalar multiplication** involves multiplying every element in a matrix by a single number (scalar). Imagine you have a grid of numbers and want to adjust each number by multiplying it with another number.

It's like you have a collection of prices and want to apply a discount or markup uniformly. The scalar would be the discount or markup percentage.

## Scalar Multiplication: Python Code

Here’s how to perform scalar multiplication in Python with NumPy:

In [ ]:
import numpy as np

# Example matrix and scalar
m1 = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2

# Scalar multiplication
result = scalar * m1
print(f'Scalar Matrix Multiplication:\n{result}')

Scalar Matrix Multiplication:
[[ 2  4  6]
 [ 8 10 12]]


* `scalar * m1` multiplies each matrix element by the scalar to produce a new matrix.

## Scalar Multiplication: Practical Example

Suppose you have a matrix representing the monthly salaries of employees in different departments. If you want to give everyone a 10% raise, you can use scalar multiplication with a scalar of 1.10.

In [ ]:
import numpy as np

# Original salaries
salaries = np.array([[3000, 4000, 5000], [6000, 7000, 8000]])

# Scalar for 10% raise
raise_factor = 1.10

# Adjusted salaries
adjusted_salaries = raise_factor * salaries
print(f'Adjusted Salaries:\n{adjusted_salaries}')

Adjusted Salaries:
[[3300. 4400. 5500.]
 [6600. 7700. 8800.]]


## Lesson Summary

We explored the basics of matrix operations, focusing on matrix addition and scalar multiplication. These operations are building blocks for complex tasks in *machine learning* and data science.

* **Matrix Addition**: Adding corresponding elements of two matrices with the same dimensions.
* **Scalar Multiplication**: Multiplying every element of a matrix by a scalar.

Understanding these operations makes future lessons involving matrices easier to grasp.

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# Dot Product and Matrix Multiplication

Welcome to our lesson on **"Dot Product and Matrix Multiplication"**! These topics are key in machine learning as they help computers process data efficiently. By the end of this lesson, you'll know what dot products and matrix multiplication are, how to calculate them, and how to implement these operations in Python.

## Dot Product

First, let's talk about the **dot product**. It's a way to combine two vectors into a single number. Think of playing a game where you multiply pairs of numbers and add the results. With numbers `[1, 2, 3]` and `[4, 5, 6]`:

* Multiply `1` by `4` to get `4`.
* Multiply `2` by `5` to get `10`.
* Multiply `3` by `6` to get `18`.
* Add them: `4 + 10 + 18 = 32`. That's the dot product!

Mathematically:
\begin{equation*}
v_1 \cdot v_2 = \sum_{i=1}^{n} v_{1i} \cdot v_{2i}
\end{equation*}

## Real-Life Example of Dot Product

Consider the scenario of calculating the total price of groceries.
* Quantities of items: `[2, 3, 1]` (for instance, 2 apples, 3 bananas, and 1 cherry)
* Prices per item: `[1.5, 0.5, 3.0]`

To find the total cost, multiply the quantities by the respective prices.
* Multiply `2` (apples) by `1.5` (\$ per apple) to get `3.0`.
* Multiply `3` (bananas) by `0.5` (\$ per banana) to get `1.5`.
* Multiply `1` (cherry) by `3.0` (\$ per cherry) to get `3.0`.

Add them: `3.0 + 1.5 + 3.0 = 7.5`. So, the total cost of groceries is \$7.5.

Mathematically, this can be expressed as the dot product of the quantity and price vectors:
\begin{equation*}
\text{Total cost} = \text{quantity} \cdot \text{price} = \sum_{i=1}^{n} \text{quantity}_i \cdot \text{price}_i
\end{equation*}

## Dot Product: Python Code

Here's how to calculate the dot product in Python using NumPy:

In [2]:
import numpy as np

# Vectors
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(f'Dot Product: {np.dot(v1, v2)}')

Dot Product: 32


This code uses NumPy's `dot` function, which directly calculates the dot product of vectors `v1` and `v2`.

## Matrix Multiplication

Next, let's talk about **matrix multiplication**. This helps combine two matrices into a new matrix. Imagine matrices as grids of numbers. Multiplying matrices combines rows and columns in a specific way. Given two matrices `A` and `B`:
\begin{equation*}
A = \begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{bmatrix}
B = \begin{bmatrix}
b_{11} & b_{12} \\
b_{21} & b_{22}
\end{bmatrix}
\end{equation*}

To find element `c_{ij}` in the resulting matrix `C`, take the dot product of the i-th row of `A` and the j-th column of `B`:
\begin{equation*}
C = \begin{bmatrix}
c_{11} & c_{12} \\
c_{21} & c_{22}
\end{bmatrix}
\end{equation*}

For example, $c_{11}$ here is a dot product of the first row of $A$ and the first column of $B$. The $c_{12}$ is a dot product of the first row of $A$ and the second column of $B$, and so on.

More specifically:
\begin{equation*}
c_{11} = a_{11} \cdot b_{11} + a_{12} \cdot b_{21}
\end{equation*}
\begin{equation*}
c_{12} = a_{11} \cdot b_{12} + a_{12} \cdot b_{22}
\end{equation*}
\begin{equation*}
c_{21} = a_{21} \cdot b_{11} + a_{22} \cdot b_{21}
\end{equation*}
\begin{equation*}
c_{22} = a_{21} \cdot b_{12} + a_{22} \cdot b_{22}
\end{equation*}

The resulting matrix `C` will have as many rows as `A` and as many columns as `B`. Think of it as "we multiply $n$ rows by $m$ columns, so the resulting matrix is of $n \times m$ shape".

## When Matrices Can Be Multiplied: Example 1

Matrix multiplication is only possible when the number of columns in matrix `A` is equal to the number of rows in matrix `B`.

Let's look at some examples:

Matrix `A` (2x3):
\begin{equation*}
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
\end{equation*}

Matrix `B` (3x2):
\begin{equation*}
B = \begin{bmatrix}
7 & 8 \\
9 & 10 \\
11 & 12
\end{bmatrix}
\end{equation*}

Matrix multiplication is possible here because the number of columns in `A` (3) is equal to the number of rows in `B` (3). The resulting matrix, `C`, will have dimensions 2x2, as we multiply 2 rows by 2 columns.

## When Matrices Can Be Multiplied: Example 2

Matrix `A` (2x3):
\begin{equation*}
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
\end{equation*}

Matrix `B` (2x2):
\begin{equation*}
B = \begin{bmatrix}
7 & 8 \\
9 & 10
\end{bmatrix}
\end{equation*}

Matrix multiplication is **not** possible here because the number of columns in `A` (3) does not equal the number of rows in `B` (2).

## When Matrices Can Be Multiplied: Example 3

Matrix `A` (2x3):
\begin{equation*}
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
\end{equation*}

Vector `v` (3x1):
\begin{equation*}
v = \begin{bmatrix}
7 \\
8 \\
9
\end{bmatrix}
\end{equation*}

Matrix multiplication is possible here because the number of columns in `A` (3) is equal to the number of rows in vector `v` (3). The resulting vector will have the dimensions 2x1, as we multiply 2 rows by 1 column.

## Real-Life Example of Matrix Multiplication

Consider a scenario where you're tracking the sales of two salespersons across three different products over two months. You have the sales data and the price per product:

Sales Matrix (`A`):
\begin{equation*}
A = \begin{bmatrix}
10 & 15 & 8 \\
12 & 18 & 5
\end{bmatrix}
\end{equation*}

Price Matrix (`B`):
\begin{equation*}
B = \begin{bmatrix}
20 \\
30 \\
50
\end{bmatrix}
\end{equation*}

To find the total revenue generated by each salesperson, you'll perform matrix multiplication:
\begin{equation*}
c_{11} = (10 \cdot 20 + 15 \cdot 30 + 8 \cdot 50) = 200 + 450 + 400 = 1050
\end{equation*}
\begin{equation*}
c_{21} = (12 \cdot 20 + 18 \cdot 30 + 5 \cdot 50) = 240 + 540 + 250 = 1030
\end{equation*}

So, the resulting revenue matrix `C` is:
\begin{equation*}
C = \begin{bmatrix}
1050 \\
1030
\end{bmatrix}
\end{equation*}

## Matrix Multiplication: Python Code

Here's how to do it in Python using NumPy:

In [3]:
import numpy as np

# Matrices
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print(f'Matrix Multiplication:\n{np.dot(m1, m2)}')

Matrix Multiplication:
[[19 22]
 [43 50]]


This code uses NumPy's `dot` function to perform matrix multiplication on matrices `m1` and `m2`, resulting in matrix `C`.

## Lesson Summary

You've learned about dot products and matrix multiplication. We covered their importance, how they work, and how to implement them in Python using NumPy. These operations are foundational in machine learning for data processing.

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# References

- **[CodeSignal: Introduction to Linear Algebra for Machine Learning Course](https://codesignal.com/learn/courses/introduction-to-linear-algebra-for-machine-learning)**

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)