# **Introduction to Linear Algebra for Machine Learning**

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# 📖 TABLE OF CONTENTS

- [Setup](#Setup)
- [Basics of Vectors and Matrices](#Basics-of-Vectors-and-Matrices)
  - [Concept: Vector](#Concept:-Vector)
  - [Creating and Displaying a Row Vector in Python](#Creating-and-Displaying-a-Row-Vector-in-Python)
  - [Creating and Displaying a Column Vector in Python](#Creating-and-Displaying-a-Column-Vector-in-Python)
  - [Concept: Matrix](#Concept:-Matrix)
  - [Creating and Displaying a Matrix in Python](#Creating-and-Displaying-a-Matrix-in-Python)
  - [Getting Dimensions in Python: Vectors](#Getting-Dimensions-in-Python:-Vectors)
  - [Getting Dimensions in Python: Matrices](#Getting-Dimensions-in-Python:-Matrices)
  - [Lesson Summary](#Lesson-Summary)
- [Basic Vector Operations](#Basic-Vector-Operations)
  - [Vector Addition: Introduction and Example](#Vector-Addition:-Introduction-and-Example)
  - [Vector Addition: Python Code](#Vector-Addition:-Python-Code)
  - [Scalar Multiplication: Introduction and Example](#Scalar-Multiplication:-Introduction-and-Example)
  - [Scalar Multiplication: Python Code](#Scalar-Multiplication:-Python-Code)
  - [Lesson Summary](#Lesson-Summary)
- [References](#References)

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# Setup

Before we jump in, let's quickly run the setup cell. It checks the environment (GPU, library versions) and sets random seeds for reproducibility — we want identical results on every run.

In [1]:
# 🔧 Setup: Run this cell first!
# Environment check + random seeds for reproducibility

import sys
import time
import random
import numpy as np
import pandas as pd
import matplotlib as mpl
import torch
import torch.nn as nn

print(f"📦 Python       {sys.version.split()[0]}")
print(f"🔢 NumPy        {np.__version__}")
print(f"🐼 Pandas       {pd.__version__}")
print(f"📊 Matplotlib   {mpl.__version__}")
print(f"🔥 PyTorch      {torch.__version__}")

# GPU check (only needed for optional deep-feature experiments)
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"✅ GPU available: {torch.cuda.get_device_name(0)}")
    print(f"   Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
else:
    device = torch.device("cpu")
    print("⚠️ No GPU detected")

DEVICE_LABEL = "GPU" if device.type == "cuda" else "CPU"

# Random seeds for reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

print(f"\n🎲 Random seed set to {SEED} (Python, NumPy, PyTorch)")

%matplotlib inline
%config InlineBackend.figure_format = 'jpeg'   # photos as JPEG, not PNG — ~10× smaller notebook
# Remove character limits for all columns of Pandas dataframes permanently in this session
pd.set_option('display.max_colwidth', None)

📦 Python       3.13.15
🔢 NumPy        2.1.3
🐼 Pandas       2.2.3
📊 Matplotlib   3.10.0
🔥 PyTorch      2.11.0+cpu
⚠️ No GPU detected

🎲 Random seed set to 42 (Python, NumPy, PyTorch)


![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# Basics of Vectors and Matrices

Welcome to our lesson on the basics of **vectors** and **matrices**!

In this lesson, we'll explore what vectors and matrices are, why they're important in machine learning, and how to create and work with them in Python. By the end of this lesson, you'll understand how to define, display, and interpret vectors and matrices. Let's get started!

## Concept: Vector

Imagine you have a list of your favorite ice cream flavors: `["vanilla", "chocolate", "strawberry"]`. A vector is such a list, but with numbers. For example, a vector could be `[1, 2, 3]`.

A vector is a list (or array) of numbers arranged in a specific order. It's one-dimensional, meaning it has only one row or one column. If a vector is a row, it is called a **row vector**. Here is an example of it:
\begin{equation*}
[1 \quad 2 \quad 3]
\end{equation*}

If a vector is a column, it is called a **column vector**:
\begin{equation*}
\begin{bmatrix}
1 \\
2 \\
3
\end{bmatrix}
\end{equation*}

They look the same, but some mathematical operations treat row vectors and column vectors differently, so it is vital to differentiate them.

## Creating and Displaying a Row Vector in Python

Let's see how we can create a row vector in Python using `np.array()` from the NumPy library. NumPy provides advanced linear algebra features that will be useful in the upcoming units of our course.

In [ ]:
import numpy as np

# Create a row vector
vector = np.array([1, 2, 3])

# Display the vector
print(f'Vector:\n{vector}')

Vector:
[1 2 3]


This shows a simple row vector with three numbers.

## Creating and Displaying a Column Vector in Python

And this is how we represent the column vector using `np.array()`:

In [ ]:
import numpy as np

# Create a column vector
vector = np.array([
    [1],
    [2],
    [3]
])

# Display the vector
print(f'Vector:\n{vector}')

Vector:
[[1]
 [2]
 [3]]


Using `np.array()`, we specify a 2-dimensional structure for the column vector, but with one item in each row.

## Concept: Matrix

Now, imagine you have a class of students, and you want to record their scores in three subjects: Math, Science, and English. You can use a matrix for this. A matrix looks like a grid, with numbers arranged in rows and columns; each number represents a score.

Here is an example matrix:
\begin{equation*}
\begin{bmatrix}
95 & 88 & 92 \\
85 & 90 & 87 \\
78 & 85 & 80
\end{bmatrix}
\end{equation*}

Each row could represent the scores for a single student, and each column – a separate subject. As we have `3` students and `3` subjects, the matrix is a square one.

Let's take this example further. Imagine there are `5` students in the class. In this case, the corresponding matrix will be rectangular:
\begin{equation*}
\begin{bmatrix}
95 & 88 & 92 \\
85 & 90 & 87 \\
78 & 85 & 80 \\
85 & 90 & 82 \\
75 & 77 & 99
\end{bmatrix}
\end{equation*}

A matrix can be of any form. In machine learning, you will mostly deal with large rectangular matrices.

## Creating and Displaying a Matrix in Python

Next, let's create a matrix using `np.array()`:

In [ ]:
import numpy as np

# Create a matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Display the matrix
print(f'Matrix:\n{matrix}')

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


This is a 3x3 matrix, represented with a 2-dimensional NumPy array.

## Getting Dimensions in Python: Vectors

Understanding the dimensions of vectors and matrices is essential for many operations in machine learning.

Let's see how to print the length of a vector:

In [ ]:
import numpy as np

# Create a row vector
row_vector = np.array([1, 2, 3])
print(f'Length of the row vector: {len(row_vector)}')

# Create a column vector
column_vector = np.array([
    [1],
    [2],
    [3]
])
print(f'Length of the column vector: {column_vector.shape[0]}')

Length of the row vector: 3
Length of the column vector: 3


For `np.array()`, the length of a row vector can be found using `len()`, and for a column vector, we use the `.shape` attribute to get the number of rows.

## Getting Dimensions in Python: Matrices

Here's how to get the number of rows and columns in a matrix:

In [ ]:
import numpy as np

# Create a matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(f'No of rows: {matrix.shape[0]}')
print(f'No of columns: {matrix.shape[1]}')

No of rows: 3
No of columns: 3


Using the `.shape` attribute of `np.array()`, we can easily access both the number of rows and columns in a matrix.

Now you know how to create and display vectors and matrices and determine their dimensions using `np.array()` from the NumPy library.

## Lesson Summary

To sum up, we’ve learned the concepts of vectors and matrices and how to create and display them in Python using `np.array()`. Vectors are one-dimensional arrays of numbers, while matrices are two-dimensional grids. Understanding these basics is crucial as they are the building blocks for many operations in machine learning.

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# Basic Vector Operations

Today, we're diving into basic **vector operations**, which are foundational to your journey in **machine learning**. Understanding these operations will help you grasp more complex concepts later on. Our goals are to learn **vector addition** and **scalar multiplication**. We'll see why these operations are essential, learn how to implement them in Python, and understand their real-world applications.

## Vector Addition: Introduction and Example

Imagine you have two lists of numbers. You want to combine them by adding corresponding numbers together. That's `vector addition`. Let's say we have vector $v_1 = [1, 2, 3]$ and vector $v_2 = [4, 5, 6]$. Adding these vectors gives us another vector where each element is the sum of the corresponding elements.

**Note:** The vectors must be of the same length to perform this addition.

So, $v_1 + v_2 = [1+4, 2+5, 3+6] = [5, 7, 9]$.

Consider two delivery trucks: Truck A and Truck B. Truck A delivers 1, 2, and 3 packages to three different locations respectively, while Truck B delivers 4, 5, and 6 packages to the same locations. By using vector addition, we can determine the total number of packages delivered to each location as follows: [1+4, 2+5, 3+6] = [5, 7, 9]. This means the total packages delivered to each location are 5, 7, and 9 respectively.

## Vector Addition: Python Code

Here's how we can implement the vector addition in python:

In [2]:
import numpy as np

# Vector addition using NumPy
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(f'Vector addition: {v1 + v2}')

Vector addition: [5 7 9]


Let's break down the code:
* `np.array([1, 2, 3])` and `np.array([4, 5, 6])` create numpy arrays for `v1` and `v2`.
* The expression `v1 + v2` performs element-wise addition, resulting in `[5, 7, 9]`.

## Scalar Multiplication: Introduction and Example

Imagine you have a list of numbers and you want to multiply each number by a constant value (scalar). For example, if $v = [2, 4, 6]$ and the scalar is 3, then multiplying each element by 3 gives us $3v = [6, 12, 18]$.

Imagine you are running a business and you have a list of product prices that are expected to increase by a fixed percentage (e.g., 20%). If the current prices are [10, 20, 30] dollars and you want to apply a 20% increase, you would multiply each price by 1.2. The new prices would be $[10 \times 1.2, 20 \times 1.2, 30 \times 1.2] = [12, 24, 36]$ dollars.

## Scalar Multiplication: Python Code

Here's the Python code for the scalar multiplication:

In [3]:
import numpy as np

# Scalar multiplication using NumPy
v1 = np.array([1, 2, 3])
scalar = 2

print(f'Scalar multiplication: {scalar * v1}')

Scalar multiplication: [2 4 6]


Explanation:
* The scalar `2` is multiplied with each element in the numpy array `v1` using the expression `scalar * v1`.
* This results in `[2*1, 2*2, 2*3]`, or `[2, 4, 6]`.

## Lesson Summary

In this lesson, we covered:
* **Vector Addition**: Combining elements from two lists element-wise.
* **Scalar Multiplication**: Multiplying each element in a list by a constant value.

These operations are fundamental in machine learning and data science. By understanding and performing them in Python, you are building a solid foundation for more advanced topics.

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)

# References

- **[CodeSignal: Introduction to Linear Algebra for Machine Learning Course](https://codesignal.com/learn/courses/introduction-to-linear-algebra-for-machine-learning)**

![rainbow](https://raw.githubusercontent.com/ancilcleetus/AI-Learning-Lab/main/assets/rainbow-divider.png)